/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_NativeLib */

#ifndef _Included_com_example_NativeLib
#define _Included_com_example_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_NativeLib
 * Method:    copyFile
 * Signature: (Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL
Java_com_example_NativeLib_copyFile
(JNIEnv
*, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
