/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tdk_jni_JniTools */

#ifndef _Included_com_tdk_jni_JniTools
#define _Included_com_tdk_jni_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tdk_jni_JniTools
 * Method:    copyByFd
 * Signature: (II)V
 */
JNIEXPORT void JNICALL
Java_com_tdk_jni_JniTools_copyByFd
(JNIEnv
*, jclass, jint, jint);

/*
 * Class:     com_tdk_jni_JniTools
 * Method:    copyByFileDescriptor
 * Signature: (Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL
Java_com_tdk_jni_JniTools_copyByFileDescriptor
(JNIEnv
*, jclass, jobject, jobject);

/*
 * Class:     com_tdk_jni_JniTools
 * Method:    copyByPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_com_tdk_jni_JniTools_copyByPath
(JNIEnv
*, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
